version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
build_script:
- ps: ./scripts/build.ps1
environment:
  APPVEYOR_REPO_TAG: true
artifacts:
- path: WebflowSharp/bin/Release/netstandard1.4
  name: netstandard16
- path: WebflowSharp/bin/Release/net45
  name: net461
skip_commits:
  message: /\[skip\]/
  files:
    - readme.md
    - LICENSE
    - .gitignore
    - .vscode/*
    - changelog.md
deploy:
- provider: NuGet
  api_key:
    secure: heegLAqxz36j7dHqBMZ6lmX0PigMsWY5/nHpGAL6A8eVr3rxjJWqm5SIdjkcRv+2
  on:
    branch: master
